### PR TITLE
Update reference.md

### PR DESCRIPTION
**Pull request by stevage**
Replace broken link. I don't know if this is the best place to point to, but the current link is broken.

### CODE REVIEW

**Comment by Bjwebb** [comment]
The 360Giving docs are now designed to be built with Sphinx, in which case the link should work.

See https://threesixtygiving-standard.readthedocs.io/en/latest/ for a built copy of the master branch.

**Comment by stevage** [comment]
OK well they don't work on the deployed site.

**Comment by Bjwebb** [comment]
Sorry, you're quite right - that needs updating on the `legacy` branch and redeploying - I'll look into that.

**Comment by stevage** [comment]
Sorry, should have been clearer up front.

**Pull request closed without merging**
