### PR TITLE
(Autumn 2017) release bugfix 

### PR DESCRIPTION
**Pull request by BobHarper1**
Asking @drkane for his review, fixes the outstanding issues in https://github.com/ThreeSixtyGiving/standard/projects/4

### CODE REVIEW

**Comment by stevieflow** [comment]
NB: I've renamed the PR and GH Project to "Autumn 2017", to avoid any confusion with version numbering, given that we don't actually have a version 1.0 released / scheduled for release

**Comment by drkane** [comment]
All looks good to me.

**Comment by BobHarper1** [comment]
Can view this version on http://threesixtygiving-standard.readthedocs.io/en/0.9-release-bugfix/ (still using the old branch name)

**Comment by BobHarper1** [comment]
Discussion for this on the 360 Forum https://forum.threesixtygiving.org/t/proposed-minor-bug-fixes-to-360giving-standard/50

**Pull request closed without merging**
