### PR TITLE
ci: Travis -> GitHub Actions

### PR DESCRIPTION
**Pull request by odscjames**

### CODE REVIEW

**Comment by odscjames** [comment]
You can see a failing one at https://github.com/ThreeSixtyGiving/standard/runs/1411633061?check_suite_focus=true

**Comment by odscjames** [comment]
[Switching from Travis to GH Actions](https://trello.com/c/oz6updTN/127-switching-from-travis-to-gh-actions)

**Comment by michaelwood** [comment]
Looks good to me, I think changes in this repo generally need oversight by 360Giving so I will leave official approval to @drkane

**Review by drkane — APPROVED** [review]
Looks great. Happy to confirm this is a non-normative change that doesn't change the substance of the standard itself.

**Pull request merged**
