### PR TITLE
Updated governance doc is now relevant for version 1.0

### PR DESCRIPTION
**Pull request by morchickit**
@stevieflow - I changed that the governance doc is now applied for version 1.0. Please have a look at the wording.

### CODE REVIEW

**Comment by stevieflow** [comment]
@morchickit sorry, I missed this

Regarding:

> "during the move from version 1.0 to 2.0"

That implies are in the process of this move / or that it is about to happen.  We are a long way off this.  Should / could this text be:

> during any future move beyond version 1.0

>?

**Comment by robredpath** [comment]
Reviewed with @mrshll1001 today. 

We believe that this is a non-normative change to normative content. I think @stevieflow 's point is a good one, and should be incorporated. There's also a typo - a `/` where there should be a `.`. 

There's an error further down where there's reference to a staff team of two, which should be removed. 

@mrshll1001 will make those updates, push, and then once approved by 360Giving staff can be merged.

**Comment by mrshll1001** [comment]
I've made the discussed changes and these should be approved before merging.

**Comment by Bjwebb** [comment]
This PR looks rather garbled, with a lot of commits that are already in master appearing. @mrshll1001 Shall I try rebasing the whole thing, see if that helps?

**Comment by Bjwebb** [comment]
Something odd was going on with GitHub's view of this pull request, merging in master seems to have fixed it.

**Comment by mrshll1001** [comment]
Closing as this appears to be an old PR, and we're now on version 1.1.2.

**Pull request closed without merging**
