### PR TITLE
Additional (publisher own) field titles - character usage

### PR DESCRIPTION
**Pull request by BobHarper1**
Re #223  'Dots in (publisher own) field titles can cause problems'.

On the 'reference' page, beneath where it says:
> If you have additional data to report that does not fit any of the columns provided in the spreadsheet, it is okay to create your own column titles in order to report it.

I've added a _hint box_ with:
> Adding your own columns:
> If you are adding your own column titles it is best to use simple titles and to avoid special characters which could cause problems in data reuse.
>  Using only lowercase and uppercase alphabetical characters (``a-z`` and ``A-Z``), numerical digits (``0-9``) colons (``:``), parentheses (``(`` and ``)``) and single spaces will help to avoid problems. Other characters could be used, but haven't been fully tested in all possible situations.

This might be a bit verbose, we could drop the last line? Also, it's the only hint box on that page, and so sticks out a bit.

### CODE REVIEW

**Comment by BobHarper1** [comment]
image

**Comment by KDuerden** [comment]
As we know dots are actually problematic, can we provide that as an example of what to avoid? I'm not sure how far people will think of full stops as 'special characters'. Eg:

Using only lowercase and uppercase alphabetical characters (a-z and A-Z), numerical digits (0-9) colons (:), parentheses (( and )) and single spaces will help to avoid problems. Full stops (.) are know to cause issues and should be avoided. Other characters could be used, but haven't been fully tested in all possible situations.

**Comment by BobHarper1** [comment]
ReadTheDocs here http://standard.threesixtygiving.org/en/223-field-titles/reference/#additional-fields (I made some changes subsequent to @stevieflow approval as I was to slow to incorporate @KDuerden additional suggestion)

If still happy will merge.

**Comment by stevieflow** [comment]
+1

**Pull request merged**
