### PR TITLE
Update governance revision

### PR DESCRIPTION
**Pull request by mariongalley**
This PATCH update will update the normative guidance about the Governance and Revision Control process text in the 360Giving Data Standard documentation.

This text has been written by members of the 360Giving team and approved by the Stewardship Committee at the June meeting. This PATCH is to make the agreed changes live in the standard documentation site.

Please can you review this from a technical perspective @mrshll1001? I'll post here once this has been approved.

### CODE REVIEW

**Comment by mrshll1001** [comment]
This is on my list to review first thing tomorrow! Once approved I'll also do the needful and iterate the version number

**Review by mrshll1001 — APPROVED** [review]
Approved. Will proceed with merge and versioning now.

**Comment by mrshll1001** [comment]
> @mrshll1001 please don't merge we need to wait to end of the week before sign off

Aha just ahead of me. I did think there was something!

**Comment by KDuerden** [comment]
I've read and check this, and I'm happy to sign off on this being merged, if we have no objections, or amends from the SC at the end of the week.

**Comment by mariongalley** [comment]
Yes, they have until end of tomorrow to comment

**Comment by mariongalley** [comment]
It's been a week since I notified the Stewardship Committee so this patch is de facto approved. Please merge @mrshll1001

**Comment by mrshll1001** [comment]
I thought I'd done this! Apologies. I've merged now, so will do the needful re iterating the PATCH number.

**Pull request merged**
