### PR TITLE
add link to new publisher registration form

### PR DESCRIPTION
**Pull request by KDuerden**
Update to change method of registering with 360Giving from emailing support@ to link to new registration form.

### CODE REVIEW

**Review by mariongalley — APPROVED** [review]
On before starting I noticed an unrelated typo:

"You will decided" should be "You will decide"

image

**Comment by KDuerden** [comment]
> On before starting I noticed an unrelated typo:
> 
> "You will decided" should be "You will decide"
> 
> image

I've fixed that now thank you.

**Comment by KDuerden** [comment]
@mrshll1001 are you ok to give a final check and merge if you agree it's ready?

**Review by mrshll1001 — APPROVED** [review]
Approved

**Pull request merged**
