### PR TITLE
Update spreadsheet template with DEI extension

### PR DESCRIPTION
**Pull request by neelima-j**
- Update 360-giving-schema-titles-with-meta-tab-2023.xlsx Meta tab
- Add DEI tab 
- Template file has not been renamed or replaced in case it is linked in multiple places

### CODE REVIEW

**Comment by KDuerden** [comment]
>* Template file has not been renamed or replaced in case it is linked in multiple places

Thank you for this. However I need a separate template which includes the DEI data fields. The file as linked above is the template that people download from the [360Giving Data Standard pages](https://standard.threesixtygiving.org/en/latest/technical/reference/#meta-sheet) will include non-standard DEI fields. As they aren't in the DEI section and may not know anything about this, this could be confusing. That template needs to be strictly based on 360Giving Data Standard and Package schema field.

Could you instead update the template - 360-giving-schema-titles-with-meta-tab-2023.xlsx - to include the new Extensions field in the Meta sheet.

The file you have prepared looks good, so this needs to be uploaded with a new name, eg - 360-giving-schema-titles-with-dei-extension-2024.xlsx, which we will then link for download from the DEI Extension guidance pages.

Apologies for not being clear about this before.

**Review by KDuerden — CHANGES_REQUESTED** [review]
I request the following changes to this PR

Remove the DEI Extension fields from the template named - 360-giving-schema-titles-with-meta-tab-2023.xlsx so it includes only 360Giving Schema and Package Schema information.

Rename the version which includes the DEI Extension fields to - 360-giving-schema-titles-with-dei-extension-2024.xlsx and save in the templates repository, so it can be linked from the DEI Extension guidance section of the documentation site.

Many thanks.

**Comment by neelima-j** [comment]
@KDuerden Ready for review: 
- 360-giving-schema-titles-with-meta-tab-2023.xlsx now has the updated meta sheet and no DEIdetails sheet. 
- 360-giving-schema-titles-with-dei-extension-2024.xlsx contains DEIdetails

**Comment by KDuerden** [comment]
> @KDuerden Ready for review:
> 
> * 360-giving-schema-titles-with-meta-tab-2023.xlsx now has the updated meta sheet and no DEIdetails sheet.
> * 360-giving-schema-titles-with-dei-extension-2024.xlsx contains DEIdetails

Thank you for doing this. I have an extra request. Excel has a nasty and annoying habit of opening with the last sheet open showing. 

In the updated version of 360-giving-schema-titles-with-meta-tab-2023.xlsx this means the file opens up in the Transactions sheet, which is basically empty apart from the Identifier field. Can you resave and upload with the Meta sheet in view when saved that way people downloading it will see a more meaningful (and less confusing) view when they open it for the first time.

Apologies for the extra step needed.

**Comment by neelima-j** [comment]
Thanks @KDuerden I fixed it manually. 
(I had a look to see if we can make the Meta tab the default automatically - it can be done with a macro, but several companies disable macros, so this is not a viable solution.)

**Comment by KDuerden** [comment]
thanks @neelima-j that is great. Much appreciated. Happy for this to go live when you're ready.

**Pull request merged**
