### PR TITLE
Add new VES currency code

### PR DESCRIPTION
**Pull request by Bjwebb**

### CODE REVIEW

**Comment by robredpath** [comment]
Technically, this looks good. However, I don't know (and I can't see from the [governance page of the docs](http://standard.threesixtygiving.org/en/latest/governance/) what the requirements about a merge on to master are from a governance perspective.

**Comment by morchickit** [comment]
What issue does it answer? Was it just a minor bug?

**Comment by Bjwebb** [comment]
The change is just to add the `VES` code to our currency codelist. (Plus some reformatting that doesn't change meaning, due to putting the schema through a script).

We should add the code, because it has been added to the ISO 4217 list which we use.

**Comment by robredpath** [comment]
Reviewed by @mrshll1001 and me today. 

This is backwards-compatible bug fix, and so should go through the PATCH process.

**Comment by drkane** [comment]
Happy to approve.

**Pull request merged**
