### PR TITLE
Package metadata (2021 branch)

### PR DESCRIPTION
**Pull request by Bjwebb**
This is a newer branch, with similar content to https://github.com/ThreeSixtyGiving/standard/pull/272

### CODE REVIEW

**Comment by KDuerden** [comment]
Hi @drkane

The metadata update approved by Standard Stewardship Committee with changes to the schema and documentation have been prepared in this pull request.

The changes agreed can be found here in the Peer Review paper - [here](https://docs.google.com/document/d/1JcPA84zBwjN48k01gITkmAgSN24BJnLLyEc6Rh_eutc/edit#heading=h.ksut49wrb8nk)

The changes are visible in these sections of the branch: 
https://standard.threesixtygiving.org/en/2021-package-metadata/reference/#spreadsheet-template
https://standard.threesixtygiving.org/en/2021-package-metadata/reference/#giving-json-schemas

I have checked this and believe it is ready to be merged into the Standard, with two variations from what was originally agreed.
The Type values and Array text in the two tables have been generated automatically from the package schema. This means they can't be edited to follow exactly what drafted in the Peer Review document. There is some learning for us here. 

A part the agreed process is "A member of the committee will verify that the changes approved in this document have been faithfully applied to the schema and documentation prior to the changes being released as a MINOR upgrade."

Hence the request to get you to review and approve.

Any questions of concerns let me know. Thank you!

**Review by drkane — APPROVED** [review]
I can verify, as a member of the stewardship committee, that the changes we agreed at the committee meeting have been faithfully applied, so happy to approve this as a MINOR upgrade to the standard.

There are a couple of very small notes that we could look at in the future:

 - as @KDuerden mentioned, the date fields are showing as "text" in the auto-generated tables. We could mitigate this by mentioning the required format in the description field. This would be consistent with other fields like "Award Date". This would probably be a PATCH upgrade
 - there's a small formatting error with the embedded JSON viewer which means it has two vertical scroll bars. I think this came up with the other JSON schema when we moved to the new theme in readthedocs - so it should be fixable, in a non-normative change.

**Comment by stevieflow** [comment]
Thanks @drkane - I've raised new issues to capture those aspects

@KDuerden it seems all is now in place to merge and move forward, but just wanted to get your nod , first of all!

**Comment by KDuerden** [comment]
> @KDuerden it seems all is now in place to merge and move forward, but just wanted to get your nod , first of all!

Yes please go ahead.

**Pull request merged**
