### PR TITLE
[#73] Removes duplicte country and currency codes from schema

### PR DESCRIPTION
**Pull request by caprenter**
As suggested those duplictes prevent the schema validating against the
https://github.com/json-schema/json-schema/blob/master/draft-04/schema

Just queuing this up. No need to merge, but would appreciate you checking.

### CODE REVIEW

**Comment by caprenter** [comment]
Also added a minor fix to the schema around the naming of 360Giving because I think that both these minor changes can be considered together

**Comment by Bjwebb** [comment]
This pull request also seems to add two copies of the JSON Schema schema, is that correct? I suspect we shouldn't be adding this at all...

**Comment by caprenter** [comment]
ah - yes that is probably a mistake. I added them locally to make sure I had not broken the schema with the alterations I had made.

As another issue, should we be adding a schema validation check as a travis test on this repository?

I'll remove those schema and update this branch

**Comment by Bjwebb** [comment]
Thanks.

Wrt. schema validation check, am I right in thinking this issue captures that - https://github.com/ThreeSixtyGiving/standard/issues/88 ?

**Comment by caprenter** [comment]
Pushed a forced update on this

**Comment by caprenter** [comment]
and yes issue #88 captures the issue on testing

**Pull request merged**
