### PR TITLE
Date validation

### PR DESCRIPTION
**Pull request by caprenter**

### CODE REVIEW

**Comment by kindly** [comment]
I do not think this should be merged yet as the 'date' format does not work with the python jsonschema library.

My suggestion would be use pattern properties for the yyyy-mm-dd format as well.

I am a little concerned about using oneOf because the errors it produces are bad (at least in the python library).  However, I see no way round this.  In cove we can get around that with some customizing the error messages.

This way we keep to the spec and do not really loose anything, bar a little bit of clarity when reading the schema as to what the regular expression means, but this is covered in the description anyway.

**Comment by BobHarper1** [comment]
Testing the CoVE branch, one of the things I've discovered is that if a date-time string is in the format `2017-11-17T11:16:15±00:00` it doesn't validate. 

The ± character is the problem (replace it with + or - it won't be a problem. 

Because so many systems might use this (this was actually taken from a current publisher) I think we need to allow it. I think it would only be used with '00:00' (±01:00 doesn't make much sense) but we'd see plenty of that because UK publishers.

The standard JSON schema 'date-time' format clearly doesn't recognise this character as valid. To solve it, I think we would need to add a regex to the `oneOf` in each date definition then that would permit.

**Comment by caprenter** [comment]
Do you know what system generated that @BobHarper1 - I would not have thought was that common - afaik it's not part of any recognised spec?

Also I don't think we're necessarily helping things by saying 'full date-time' e.g. here
https://github.com/ThreeSixtyGiving/standard/pull/128/files#diff-301b7052607251679c5a059ffe27885aR634

what does 'full date-time' mean - where is it defined? (as opposed to e.g. The date must be in ISO 8601 format (YYYY-MM-DD) - which specifies both a standard and a format defined within that standard)

**Comment by BobHarper1** [comment]
@caprenter I'm not sure what system is generating that (if it is a system). I chose a dataset completely at random from the data registry ([London Councils](http://www.londoncouncils.gov.uk/node/32831)) and it happened to be using that (but it'll work fine as an Excel, it's once it's converted to a CSV string that the problem crops up).

Perhaps it's not a system that's generated it. It could have been created as a concatenation where the publisher has seen 'yyyy-mm-ddThh:mm:ss±hh:mm' (the ± actually means **+ or -**) and pasted that in? Wild speculation, but possible.

Re "Full date-time", doesn't really mean anything different to "date-time format". I think it's just over-emphasising.

**Comment by Bjwebb** [comment]
Sounds possible. I think allowing ± is a bad idea, because it will cause hassle for most data consumers.

**Comment by BobHarper1** [comment]
Ben's right. Obviously, some publishers will have to make sure they're not using ±  (if we're super lucky I've just identified the only one).

**Pull request merged**
